name: Create A Release 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "main"
          git-release-bot-name: "release-bot"
          access-token: ${{ secrets.MY_TOKEN }}
          maven-args: "-Dmaven.javadoc.skip=true -Dmaven.test.skipTests=true -Dmaven.test.skip=true -Ddockerfile.skip -DdockerCompose.skip -Dusername=summit"
